[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/followup"
  to = "/.netlify/functions/followup"
  status = 200

[[redirects]]
  from = "/api/ai/followup"
  to = "/.netlify/functions/followup"
  status = 200

[[redirects]]
  from = "/api/ai/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# netlify.toml
[dev]
  # this tells Netlify Dev to look for your Vite app on 8080 instead of 5173
  targetPort = 8080
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "default-src 'self'; script-src 'self' https://maps.googleapis.com https://maps.gstatic.com 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://maps.googleapis.com; img-src 'self' data: https://maps.googleapis.com https://maps.gstatic.com https://ceqpdprcqhmkqdbgmmkn.supabase.co; connect-src 'self' https://maps.googleapis.com https://maps.gstatic.com https://api.mapbox.com https://events.mapbox.com https://api.openai.com https://ceqpdprcqhmkqdbgmmkn.supabase.co; font-src 'self' https://fonts.gstatic.com; frame-src https://www.google.com https://maps.googleapis.com https://maps.gstatic.com;"
